import React, { createContext, useState, useContext, ReactNode } from 'react';

type Language = 'EN' | 'PT' | 'ES';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  EN: {
    // Navbar
    "nav.features": "Features",
    "nav.howItWorks": "How It Works",
    "nav.dashboard": "Dashboard",
    "nav.pricing": "Pricing",
    "nav.enterprise": "Enterprise",
    "nav.getStarted": "Get Started",
    
    // Hero
    "hero.badge": "New: AI Question Generator",
    "hero.title.1": "Grading & Creation",
    "hero.title.2": "automated.",
    "hero.subtitle": "From creating quizzes with AI to grading bubble sheets in seconds. The all-in-one platform for modern education.",
    "hero.startFree": "Start for Free",
    "hero.viewDemo": "View Demo",
    "hero.pill.camera": "Camera Correction",
    "hero.pill.quiz": "AI Quiz Creator",
    "hero.dash.overview": "Overview",
    "hero.dash.creator": "AI Creator",
    "hero.dash.gradebook": "Gradebook",
    "hero.dash.avgScore": "Avg Score",
    "hero.dash.pending": "Pending",
    "hero.dash.attendance": "Attendance",
    "hero.dash.requiresReview": "Requires Review",
    "hero.dash.subjectMastery": "Subject Mastery",
    "hero.gen.placeholder": "Create a quiz on Photosynthesis...",
    "hero.gen.question": "What is the primary output of photosynthesis?",
    
    // Trusted By (New)
    "trusted.title": "Trusted by innovative teams",
    "trusted.subtitle": "Join 500+ institutions modernizing their evaluation process.",

    // Features
    "features.eyebrow": "Features",
    "features.title.1": "Everything you need to",
    "features.title.2": "grade smarter.",
    "features.subtitle": "Our platform combines powerful AI with a delightful interface to make grading the easiest part of your day.",
    "feat.vision.title": "Computer Vision Scanning",
    "feat.vision.desc": "Advanced OCR and image processing algorithms digitize handwritten essays and bubble sheets with 99.8% accuracy.",
    "feat.realtime.title": "Real-Time Evaluation",
    "feat.realtime.desc": "Instantaneous processing means grades are ready seconds after submission, providing immediate feedback loops.",
    "feat.analytics.title": "Deep Analytics",
    "feat.analytics.desc": "Move beyond simple scores. Identify knowledge gaps, track class trends, and visualize performance growth over time.",
    "feat.criteria.title": "Standardized Criteria",
    "feat.criteria.desc": "Ensure fairness with AI that applies consistent grading rubrics across every single paper, eliminating bias.",
    "feat.scale.title": "Global Scalability",
    "feat.scale.desc": "Built for scale. Whether for a single classroom or a multinational corporation, our infrastructure adapts to your needs.",
    "feat.workload.title": "Workload Reduction",
    "feat.workload.desc": "Reclaim hundreds of hours per semester. Let AI handle the grading while you focus on mentorship.",
    "stats.gradingTime": "Reduction in Grading Time",
    "stats.papers": "Papers Processed Daily",
    "stats.accuracy": "Accuracy Rate",
    "stats.uptime": "System Availability",

    // Paper To Digital
    "p2d.eyebrow": "Digitization Workflow",
    "p2d.title.1": "Physical to Digital",
    "p2d.title.2": "in milliseconds.",
    "p2d.subtitle": "Watch how our computer vision pipeline transforms physical exam papers into structured, analyzable data.",
    "p2d.rawInput": "Raw Input",
    "p2d.processing": "Processing",
    "p2d.structuredData": "Structured Data",
    "p2d.insights": "Instant Insights",
    "p2d.genReport": "Generating Report...",

    // How It Works
    "hiw.eyebrow": "Mobile Scanner",
    "hiw.title.1": "Correct bubble sheets with",
    "hiw.title.2": "just your camera.",
    "hiw.score": "Score",
    "hiw.step1.title": "Point & Capture",
    "hiw.step1.desc": "Use the mobile app to scan tests. No special scanners required—just your smartphone.",
    "hiw.step2.title": "Instant Correction",
    "hiw.step2.desc": "Our computer vision identifies filled bubbles instantly. It handles partial erasures and scribbles with 99% accuracy.",
    "hiw.step3.title": "Auto-Gradebook",
    "hiw.step3.desc": "Scores are automatically synced to your digital gradebook. No manual data entry ever again.",

    // Essay Grading
    "essay.badge": "AI Essay Grading",
    "essay.title": "Detailed feedback on every sentence.",
    "essay.subtitle": "Our AI reads specifically for your rubric. It highlights grammar errors, detects thesis strength, and provides actionable feedback for students automatically.",
    "essay.card.correction.title": "Correction",
    "essay.card.correction.desc": "Identifies grammar, syntax, and factual errors instantly.",
    "essay.card.praise.title": "Praise",
    "essay.card.praise.desc": "Highlights strong arguments and good evidence usage.",
    "essay.doc.title": "The Impact of the Industrial Revolution",
    "essay.doc.p1": "The Industrial Revolution was a period of major industrialization that took place during the late 1700s and early 1800s.",
    "essay.doc.highlight1": "It began in Great Britain and quickly spread to the world.",
    "essay.doc.p2": "This time period saw the mechanization of agriculture and textile manufacturing and a revolution in power.",
    "essay.doc.p3": "However, there were many negative affects.",
    "essay.doc.highlight2": "The pollution was very bad and caused issues.",
    "essay.doc.p4": "While economic growth was achieved, the social cost was high for the working class living in crowded cities.",
    "essay.sidebar.title": "AI Feedback",
    "essay.sidebar.tooltip.title": "How it works",
    "essay.sidebar.tooltip.desc": "Our Natural Language Processing models are trained on thousands of academic rubrics to detect argumentative structure, factual consistency, and stylistic nuance.",
    "essay.feedback.thesis": "Strong Thesis",
    "essay.feedback.thesis.desc": "Clear opening statement identifying key time periods.",
    "essay.feedback.vocab": "Vocabulary",
    "essay.feedback.vocab.desc": "\"Very bad\" is vague. Consider \"detrimental\" or \"hazardous\".",
    "essay.score": "Score",

    // Class Analytics
    "analytics.chart.title": "Skill Gap Analysis",
    "analytics.chart.subtitle": "Student vs. Class Average",
    "analytics.chart.class": "Class",
    "analytics.chart.student": "Student",
    "analytics.alert.title": "Intervention Needed",
    "analytics.alert.desc": "Vocabulary scores are 20% below class average.",
    "analytics.badge": "Targeted Growth",
    "analytics.title.1": "Don't just grade.",
    "analytics.title.2": "Understand.",
    "analytics.subtitle": "Go beyond a simple letter grade. Our analytics engine breaks down performance by specific skills and learning objectives, helping you spot struggling students before they fall behind.",
    "analytics.card1.title": "Skill Mastery",
    "analytics.card1.desc": "Track proficiency in specific topics like 'Critical Thinking' or 'Algebra'.",
    "analytics.card2.title": "Trend Spotting",
    "analytics.card2.desc": "Visualize progress over the semester to validate teaching methods.",
    // Topics & Insights
    "analytics.topic.grammar": "Grammar",
    "analytics.topic.logic": "Logic",
    "analytics.topic.creativity": "Creativity",
    "analytics.topic.evidence": "Evidence",
    "analytics.topic.structure": "Structure",
    "analytics.topic.vocab": "Vocab",
    "analytics.insight.grammar": "Strong command of syntax rules.",
    "analytics.insight.logic": "Argument flow is slightly inconsistent.",
    "analytics.insight.creativity": "Unique perspective, well presented.",
    "analytics.insight.evidence": "Citations are accurate and relevant.",
    "analytics.insight.structure": "Paragraph transitions need work.",
    "analytics.insight.vocab": "Repetitive word choice detected.",

    // Curriculum Breakdown
    "curr.eyebrow": "Granular Curriculum Insights",
    "curr.title": "Performance from Area to Topic",
    "curr.subtitle": "Drill down into your institution's data. See exactly which specific contents—like the 'Industrial Revolution'—students are mastering and where they need help.",
    "curr.col1": "Area of Study",
    "curr.col2": "Discipline",
    "curr.col3": "Specific Topics",
    "curr.area.humanities": "Humanities",
    "curr.area.stem": "STEM",
    "curr.disc.history": "History",
    "curr.disc.geography": "Geography",
    "curr.disc.math": "Mathematics",
    "curr.disc.physics": "Physics",
    "curr.topic.indrev": "Industrial Revolution",
    "curr.topic.stoneage": "Stone Age",
    "curr.topic.coldwar": "Cold War",
    "curr.topic.mapreading": "Map Reading",
    "curr.topic.urban": "Urban Planning",
    "curr.topic.algebra": "Linear Algebra",
    "curr.topic.calc": "Calculus I",
    "curr.topic.mech": "Mechanics",
    "curr.topic.thermo": "Thermodynamics",
    "curr.metric.efficiency": "Efficiency",
    "curr.metric.mastery": "Mastery",
    "curr.badge.custom": "Customizable",
    "curr.btn.edit": "Edit View",
    "curr.btn.done": "Done",
    "curr.btn.drill": "Drill Down",

    // Parent Portal
    "parent.badge": "Parent Engagement",
    "parent.title.1": "Keep parents in the loop,",
    "parent.title.2": "automatically.",
    "parent.subtitle": "Bridge the gap between home and school. Evalua provides a dedicated mobile portal for guardians to view real-time grades, attendance, and teacher feedback without waiting for report cards.",
    "parent.list.1": "Instant push notifications for assignments",
    "parent.list.2": "Secure, direct teacher messaging",
    "parent.list.3": "Digital student portfolio access",
    "parent.btn.enable": "Enable Parent Access",
    "parent.btn.demo": "Send Live Update",
    "parent.demo.hint": "Tap \"Send Live Update\" to interact with the demo.",
    "parent.phone.header": "Parent Portal",
    "parent.phone.sub": "My Students",
    "parent.notif.grade.title": "New Grade Posted",
    "parent.notif.grade.sub": "Math Midterm",
    "parent.notif.event.title": "Upcoming Event",
    "parent.notif.event.sub": "Science Fair",
    "parent.nav.feed": "Feed",
    "parent.nav.plan": "Plan",
    "parent.nav.chat": "Chat",

    // Dashboard Preview
    "dash.eyebrow": "Executive Overview",
    "dash.title": "Data that drives better decisions.",
    "dash.subtitle": "For administrators and department heads, get a bird's-eye view of institutional performance. Track progress over time, compare cohorts, and export data for accreditation.",
    "dash.list.1": "Automatic rubric alignment",
    "dash.list.2": "Plagiarism detection alerts",
    "dash.list.3": "Longitudinal performance tracking",
    "dash.list.4": "Seamless LMS Integration",
    "dash.btn": "Explore Analytics",
    "dash.vis.header": "Institution Performance",
    "dash.vis.period": "Last 30 Days",
    "dash.vis.avg": "Avg Score",
    "dash.vis.graded": "Graded",
    "dash.vis.pending": "Pending",

    // Pricing
    "pricing.eyebrow": "Plans & Pricing",
    "pricing.title": "Simple pricing for",
    "pricing.title.span": "every classroom.",
    "pricing.subtitle": "Choose the plan that fits your needs. No hidden fees, cancel anytime.",
    "pricing.monthly": "Monthly",
    "pricing.yearly": "Yearly",
    "pricing.save": "Save 20%",
    "pricing.free.title": "Free",
    "pricing.free.price": "$0",
    "pricing.free.period": "/mo",
    "pricing.free.desc": "Perfect for individual teachers trying out AI grading.",
    "pricing.free.btn": "Get Started",
    "pricing.free.f1": "Mobile App Access",
    "pricing.free.f2": "100 Papers / month",
    "pricing.free.f3": "Basic Bubble Sheet Grading",
    "pricing.free.f4": "Email Support",
    "pricing.pro.title": "Pro",
    "pricing.pro.price": "$29",
    "pricing.pro.period": "/mo",
    "pricing.pro.desc": "For power users who need advanced analytics and essay grading.",
    "pricing.pro.btn": "Start Free Trial",
    "pricing.pro.badge": "Most Popular",
    "pricing.pro.f1": "Unlimited Papers",
    "pricing.pro.f2": "AI Essay Grading",
    "pricing.pro.f3": "Class Analytics & Insights",
    "pricing.pro.f4": "Parent Portal Access",
    "pricing.pro.f5": "LMS Export (CSV)",
    "pricing.ent.title": "Enterprise",
    "pricing.ent.price": "Custom",
    "pricing.ent.period": "",
    "pricing.ent.desc": "For schools and districts requiring SSO and custom integrations.",
    "pricing.ent.btn": "Contact Sales",
    "pricing.ent.f1": "Everything in Pro",
    "pricing.ent.f2": "SSO & Custom Security",
    "pricing.ent.f3": "Direct LMS Integration",
    "pricing.ent.f4": "District-wide Analytics",
    "pricing.ent.f5": "Dedicated Success Manager",

    // Enterprise
    "ent.eyebrow": "Enterprise Edition",
    "ent.title": "Built for scale, secured for institutions.",
    "ent.subtitle": "Custom deployment options, SSO integration, and SLA-backed guarantees for districts and universities.",
    "ent.btn": "Contact Sales",
    "ent.feat1.title": "Bank-Grade Security",
    "ent.feat1.desc": "Your student data is encrypted at rest and in transit. We are SOC2 Type II compliant and FERPA certified.",
    "ent.feat1.l1": "SOC2 Type II Compliant",
    "ent.feat1.l2": "FERPA & GDPR Ready",
    "ent.feat1.l3": "End-to-End Encryption",
    "ent.feat2.title": "Seamless SSO",
    "ent.feat2.desc": "Integrate with your existing identity provider. We support SAML, OAuth, and OIDC out of the box.",
    "ent.feat3.title": "Private Infrastructure",
    "ent.feat3.desc": "Option for dedicated VPC deployment or on-premise containerization for maximum data sovereignty.",
    "ent.feat3.l1": "99.99% Uptime SLA",
    "ent.feat3.l2": "Dedicated Success Manager",
    "ent.feat3.l3": "Custom API Rate Limits",
    "ent.integrations": "Works with the tools you already use",

    // CTA
    "cta.title": "Ready to modernize your evaluation process?",
    "cta.subtitle": "Join over 500 educational institutions saving time with Evalua AI.",
    "cta.btn.start": "Get Started Free",
    "cta.btn.sales": "Contact Sales",

    // Footer
    "footer.desc": "Empowering educators with high-accuracy, automated evaluation systems. Built for modern institutions and corporate training.",
    "footer.platform": "Platform",
    "footer.company": "Company",
    "footer.rights": "© 2024 Evalua AI Inc. All rights reserved."
  },
  PT: {
    // Navbar
    "nav.features": "Funcionalidades",
    "nav.howItWorks": "Como Funciona",
    "nav.dashboard": "Painel",
    "nav.pricing": "Preços",
    "nav.enterprise": "Empresas",
    "nav.getStarted": "Começar",
    
    // Hero
    "hero.badge": "Novo: Gerador de Questões com IA",
    "hero.title.1": "Correção e Criação",
    "hero.title.2": "automatizadas.",
    "hero.subtitle": "Desde criar quizzes com IA até corrigir gabaritos em segundos. A plataforma tudo-em-um para a educação moderna.",
    "hero.startFree": "Comece Grátis",
    "hero.viewDemo": "Ver Demo",
    "hero.pill.camera": "Correção por Câmera",
    "hero.pill.quiz": "Criador de Quiz IA",
    "hero.dash.overview": "Visão Geral",
    "hero.dash.creator": "Criador IA",
    "hero.dash.gradebook": "Boletim",
    "hero.dash.avgScore": "Média",
    "hero.dash.pending": "Pendentes",
    "hero.dash.attendance": "Frequência",
    "hero.dash.requiresReview": "Requer Revisão",
    "hero.dash.subjectMastery": "Domínio do Assunto",
    "hero.gen.placeholder": "Criar um quiz sobre Fotossíntese...",
    "hero.gen.question": "Qual é o principal produto da fotossíntese?",

    // Trusted By
    "trusted.title": "Confiado por equipes inovadoras",
    "trusted.subtitle": "Junte-se a mais de 500 instituições modernizando seu processo de avaliação.",

    // Features
    "features.eyebrow": "Funcionalidades",
    "features.title.1": "Tudo o que você precisa para",
    "features.title.2": "avaliar melhor.",
    "features.subtitle": "Nossa plataforma combina IA poderosa com uma interface agradável para tornar a correção a parte mais fácil do seu dia.",
    "feat.vision.title": "Escaneamento por Visão Computacional",
    "feat.vision.desc": "Algoritmos avançados de OCR digitalizam redações manuscritas e gabaritos com 99,8% de precisão.",
    "feat.realtime.title": "Avaliação em Tempo Real",
    "feat.realtime.desc": "Processamento instantâneo significa notas prontas segundos após o envio, fornecendo feedback imediato.",
    "feat.analytics.title": "Analytics Profundo",
    "feat.analytics.desc": "Vá além das notas simples. Identifique lacunas de conhecimento, acompanhe tendências da turma e visualize o crescimento.",
    "feat.criteria.title": "Critérios Padronizados",
    "feat.criteria.desc": "Garanta justiça com IA que aplica rubricas de correção consistentes em cada prova, eliminando viés.",
    "feat.scale.title": "Escalabilidade Global",
    "feat.scale.desc": "Feito para escalar. Seja para uma única sala de aula ou uma multinacional, nossa infraestrutura se adapta.",
    "feat.workload.title": "Redução de Carga de Trabalho",
    "feat.workload.desc": "Recupere centenas de horas por semestre. Deixe a IA lidar com a correção enquanto você foca na mentoria.",
    "stats.gradingTime": "Redução no Tempo de Correção",
    "stats.papers": "Provas Processadas Diariamente",
    "stats.accuracy": "Taxa de Precisão",
    "stats.uptime": "Disponibilidade do Sistema",

    // Paper To Digital
    "p2d.eyebrow": "Fluxo de Digitalização",
    "p2d.title.1": "Físico para Digital",
    "p2d.title.2": "em milissegundos.",
    "p2d.subtitle": "Veja como nossa visão computacional transforma provas físicas em dados estruturados e analisáveis.",
    "p2d.rawInput": "Entrada Bruta",
    "p2d.processing": "Processando",
    "p2d.structuredData": "Dados Estruturados",
    "p2d.insights": "Insights Instantâneos",
    "p2d.genReport": "Gerando Relatório...",

    // How It Works
    "hiw.eyebrow": "Scanner Móvel",
    "hiw.title.1": "Corrija gabaritos com",
    "hiw.title.2": "apenas sua câmera.",
    "hiw.score": "Nota",
    "hiw.step1.title": "Aponte e Capture",
    "hiw.step1.desc": "Use o aplicativo móvel para escanear testes. Sem scanners especiais—apenas seu smartphone.",
    "hiw.step2.title": "Correção Instantânea",
    "hiw.step2.desc": "Nossa visão computacional identifica bolhas preenchidas instantaneamente. Lida com rasuras e rascunhos com 99% de precisão.",
    "hiw.step3.title": "Boletim Automático",
    "hiw.step3.desc": "As notas são sincronizadas automaticamente com seu boletim digital. Nunca mais digite dados manualmente.",

    // Essay Grading
    "essay.badge": "Correção de Redação IA",
    "essay.title": "Feedback detalhado em cada frase.",
    "essay.subtitle": "Nossa IA lê especificamente para sua rubrica. Ela destaca erros gramaticais, detecta a força da tese e fornece feedback acionável.",
    "essay.card.correction.title": "Correção",
    "essay.card.correction.desc": "Identifica erros gramaticales, sintáticos e factuais instantaneamente.",
    "essay.card.praise.title": "Elogio",
    "essay.card.praise.desc": "Destaca argumentos fortes e bom uso de evidências.",
    "essay.doc.title": "O Impacto da Revolução Industrial",
    "essay.doc.p1": "A Revolução Industrial foi um período de grande industrialização que ocorreu durante o final dos anos 1700 e início dos anos 1800.",
    "essay.doc.highlight1": "Começou na Grã-Bretanha e rapidamente se espalhou para o mundo.",
    "essay.doc.p2": "Este período viu a mecanização da agricultura e manufatura têxtil e uma revolução na energia.",
    "essay.doc.p3": "No entanto, houve muitos efeitos negativos.",
    "essay.doc.highlight2": "A poluição era muito ruim e causou problemas.",
    "essay.doc.p4": "Embora o crescimento econômico tenha sido alcançado, o custo social foi alto para a classe trabalhadora vivendo em cidades lotadas.",
    "essay.sidebar.title": "Feedback da IA",
    "essay.sidebar.tooltip.title": "Como funciona",
    "essay.sidebar.tooltip.desc": "Nossos modelos de Processamento de Linguagem Natural são treinados em milhares de rubricas acadêmicas para detectar estrutura argumentativa e consistência factual.",
    "essay.feedback.thesis": "Tese Forte",
    "essay.feedback.thesis.desc": "Declaração de abertura clara identificando períodos-chave.",
    "essay.feedback.vocab": "Vocabulário",
    "essay.feedback.vocab.desc": "\"Muito ruim\" é vago. Considere \"prejudicial\" ou \"nocivo\".",
    "essay.score": "Nota",

    // Class Analytics
    "analytics.chart.title": "Análise de Lacunas",
    "analytics.chart.subtitle": "Aluno vs. Média da Turma",
    "analytics.chart.class": "Turma",
    "analytics.chart.student": "Aluno",
    "analytics.alert.title": "Intervenção Necessária",
    "analytics.alert.desc": "Notas de vocabulário estão 20% abaixo da média da turma.",
    "analytics.badge": "Crescimento Focado",
    "analytics.title.1": "Não apenas dê nota.",
    "analytics.title.2": "Entenda.",
    "analytics.subtitle": "Vá além de uma simples nota. Nosso motor analítico divide o desempenho por habilidades específicas, ajudando você a identificar alunos com dificuldades.",
    "analytics.card1.title": "Domínio de Habilidades",
    "analytics.card1.desc": "Acompanhe a proficiência em tópicos específicos como 'Pensamento Crítico' ou 'Álgebra'.",
    "analytics.card2.title": "Tendências",
    "analytics.card2.desc": "Visualize o progresso ao longo do semestre para validar métodos de ensino.",
    // Topics & Insights
    "analytics.topic.grammar": "Gramática",
    "analytics.topic.logic": "Lógica",
    "analytics.topic.creativity": "Criatividade",
    "analytics.topic.evidence": "Evidência",
    "analytics.topic.structure": "Estrutura",
    "analytics.topic.vocab": "Vocabulário",
    "analytics.insight.grammar": "Forte domínio das regras de sintaxe.",
    "analytics.insight.logic": "O fluxo de argumentos é ligeiramente inconsistente.",
    "analytics.insight.creativity": "Perspectiva única, bem apresentada.",
    "analytics.insight.evidence": "As citações são precisas e relevantes.",
    "analytics.insight.structure": "As transições de parágrafo precisam de trabalho.",
    "analytics.insight.vocab": "Escolha de palavras repetitiva detectada.",

    // Curriculum Breakdown
    "curr.eyebrow": "Insights Curriculares",
    "curr.title": "Desempenho da Área ao Tópico",
    "curr.subtitle": "Aprofunde-se nos dados. Veja exatamente quais conteúdos específicos—como a 'Revolução Industrial'—os alunos estão dominando.",
    "curr.col1": "Área de Estudo",
    "curr.col2": "Disciplina",
    "curr.col3": "Tópicos Específicos",
    "curr.area.humanities": "Humanas",
    "curr.area.stem": "Exatas/STEM",
    "curr.disc.history": "História",
    "curr.disc.geography": "Geografia",
    "curr.disc.math": "Matemática",
    "curr.disc.physics": "Física",
    "curr.topic.indrev": "Revolução Industrial",
    "curr.topic.stoneage": "Idade da Pedra",
    "curr.topic.coldwar": "Guerra Fria",
    "curr.topic.mapreading": "Leitura de Mapas",
    "curr.topic.urban": "Planejamento Urbano",
    "curr.topic.algebra": "Álgebra Linear",
    "curr.topic.calc": "Cálculo I",
    "curr.topic.mech": "Mecânica",
    "curr.topic.thermo": "Termodinâmica",
    "curr.metric.efficiency": "Eficiência",
    "curr.metric.mastery": "Domínio",
    "curr.badge.custom": "Personalizável",
    "curr.btn.edit": "Editar Layout",
    "curr.btn.done": "Pronto",
    "curr.btn.drill": "Detalhar",

    // Parent Portal
    "parent.badge": "Engajamento dos Pais",
    "parent.title.1": "Mantenha os pais informados,",
    "parent.title.2": "automaticamente.",
    "parent.subtitle": "Uma ponte entre casa e escola. O Evalua fornece um portal móvel dedicado para responsáveis verem notas, frequência e feedback em tempo real.",
    "parent.list.1": "Notificações instantâneas para tarefas",
    "parent.list.2": "Mensagens diretas e seguras com professores",
    "parent.list.3": "Acesso ao portfólio digital do aluno",
    "parent.btn.enable": "Habilitar Acesso aos Pais",
    "parent.btn.demo": "Enviar Atualização",
    "parent.demo.hint": "Toque em \"Enviar Atualização\" para interagir com a demonstração.",
    "parent.phone.header": "Portal dos Pais",
    "parent.phone.sub": "Meus Alunos",
    "parent.notif.grade.title": "Nova Nota Postada",
    "parent.notif.grade.sub": "Matemática Intermediária",
    "parent.notif.event.title": "Evento Próximo",
    "parent.notif.event.sub": "Feira de Ciências",
    "parent.nav.feed": "Feed",
    "parent.nav.plan": "Plano",
    "parent.nav.chat": "Chat",

    // Dashboard Preview
    "dash.eyebrow": "Visão Executiva",
    "dash.title": "Dados que impulsionam melhores decisões.",
    "dash.subtitle": "Para administradores e chefes de departamento, obtenha uma visão geral do desempenho institucional. Acompanhe o progresso ao longo do tempo e compare coortes.",
    "dash.list.1": "Alinhamento automático de rubrica",
    "dash.list.2": "Alertas de detecção de plágio",
    "dash.list.3": "Acompanhamento longitudinal de desempenho",
    "dash.list.4": "Integração perfeita com LMS",
    "dash.btn": "Explorar Analytics",
    "dash.vis.header": "Desempenho da Instituição",
    "dash.vis.period": "Últimos 30 Dias",
    "dash.vis.avg": "Média",
    "dash.vis.graded": "Corrigidos",
    "dash.vis.pending": "Pendentes",

    // Pricing
    "pricing.eyebrow": "Planos e Preços",
    "pricing.title": "Preço simples para",
    "pricing.title.span": "toda sala de aula.",
    "pricing.subtitle": "Escolha o plano que atende às suas necessidades. Sem taxas ocultas, cancele a qualquer momento.",
    "pricing.monthly": "Mensal",
    "pricing.yearly": "Anual",
    "pricing.save": "Economize 20%",
    "pricing.free.title": "Grátis",
    "pricing.free.price": "R$0",
    "pricing.free.period": "/mês",
    "pricing.free.desc": "Perfeito para professores individuais testando correção por IA.",
    "pricing.free.btn": "Começar",
    "pricing.free.f1": "Acesso ao App Móvel",
    "pricing.free.f2": "100 Provas / mês",
    "pricing.free.f3": "Correção Básica de Gabarito",
    "pricing.free.f4": "Suporte por Email",
    "pricing.pro.title": "Pro",
    "pricing.pro.price": "R$99",
    "pricing.pro.period": "/mês",
    "pricing.pro.desc": "Para usuários avançados que precisam de analytics e correção de redação.",
    "pricing.pro.btn": "Teste Grátis",
    "pricing.pro.badge": "Mais Popular",
    "pricing.pro.f1": "Provas Ilimitadas",
    "pricing.pro.f2": "Correção de Redação IA",
    "pricing.pro.f3": "Analytics de Turma",
    "pricing.pro.f4": "Portal dos Pais",
    "pricing.pro.f5": "Exportação LMS (CSV)",
    "pricing.ent.title": "Enterprise",
    "pricing.ent.price": "Sob Medida",
    "pricing.ent.period": "",
    "pricing.ent.desc": "Para escolas e distritos que exigem SSO e integrações personalizadas.",
    "pricing.ent.btn": "Contatar Vendas",
    "pricing.ent.f1": "Tudo do Pro",
    "pricing.ent.f2": "SSO e Segurança Personalizada",
    "pricing.ent.f3": "Integração LMS Direta",
    "pricing.ent.f4": "Analytics Distrital",
    "pricing.ent.f5": "Gerente de Sucesso Dedicado",

    // Enterprise
    "ent.eyebrow": "Edição Enterprise",
    "ent.title": "Feito para escala, seguro para instituições.",
    "ent.subtitle": "Opções de implantação personalizadas, integração SSO e garantias de SLA para distritos e universidades.",
    "ent.btn": "Contatar Vendas",
    "ent.feat1.title": "Segurança Bancária",
    "ent.feat1.desc": "Seus dados de alunos são criptografados em repouso e em trânsito. Somos compatíveis com SOC2 Tipo II e certificados FERPA.",
    "ent.feat1.l1": "Compatível com SOC2 Tipo II",
    "ent.feat1.l2": "Pronto para FERPA e LGPD",
    "ent.feat1.l3": "Criptografia de ponta a ponta",
    "ent.feat2.title": "SSO Integrado",
    "ent.feat2.desc": "Integre com seu provedor de identidade existente. Suportamos SAML, OAuth e OIDC nativamente.",
    "ent.feat3.title": "Infraestrutura Privada",
    "ent.feat3.desc": "Opção de implantação em VPC dedicada ou containerização local para máxima soberania de dados.",
    "ent.feat3.l1": "SLA de 99,99% de Uptime",
    "ent.feat3.l2": "Gerente de Sucesso Dedicado",
    "ent.feat3.l3": "Limites de API Personalizados",
    "ent.integrations": "Funciona com as ferramentas que você já usa",

    // CTA
    "cta.title": "Pronto para modernizar seu processo de avaliação?",
    "cta.subtitle": "Junte-se a mais de 500 instituições educacionais economizando tempo com o Evalua AI.",
    "cta.btn.start": "Começar Grátis",
    "cta.btn.sales": "Contatar Vendas",

    // Footer
    "footer.desc": "Empoderando educadores com sistemas de avaliação automatizada de alta precisão. Feito para instituições modernas.",
    "footer.platform": "Plataforma",
    "footer.company": "Empresa",
    "footer.rights": "© 2024 Evalua AI Inc. Todos os direitos reservados."
  },
  ES: {
    // Navbar
    "nav.features": "Funcionalidades",
    "nav.howItWorks": "Cómo Funciona",
    "nav.dashboard": "Panel",
    "nav.pricing": "Precios",
    "nav.enterprise": "Empresas",
    "nav.getStarted": "Empezar",
    
    // Hero
    "hero.badge": "Nuevo: Generador de Preguntas con IA",
    "hero.title.1": "Calificación y Creación",
    "hero.title.2": "automatizadas.",
    "hero.subtitle": "Desde crear cuestionarios con IA hasta calificar hojas de respuestas en segundos. La plataforma todo en uno para la educación moderna.",
    "hero.startFree": "Empieza Gratis",
    "hero.viewDemo": "Ver Demo",
    "hero.pill.camera": "Corrección por Cámara",
    "hero.pill.quiz": "Creador de Quiz IA",
    "hero.dash.overview": "Resumen",
    "hero.dash.creator": "Creador IA",
    "hero.dash.gradebook": "Libreta",
    "hero.dash.avgScore": "Promedio",
    "hero.dash.pending": "Pendiente",
    "hero.dash.attendance": "Asistencia",
    "hero.dash.requiresReview": "Requiere Revisión",
    "hero.dash.subjectMastery": "Dominio del Tema",
    "hero.gen.placeholder": "Crear un quiz sobre Fotosíntesis...",
    "hero.gen.question": "¿Cuál es el producto principal de la fotosíntesis?",

    // Trusted By
    "trusted.title": "Con la confianza de equipos innovadores",
    "trusted.subtitle": "Únete a más de 500 instituciones que modernizan su proceso de evaluación.",

    // Features
    "features.eyebrow": "Funcionalidades",
    "features.title.1": "Todo lo que necesitas para",
    "features.title.2": "calificar mejor.",
    "features.subtitle": "Nuestra plataforma combina una potente IA con una interfaz agradable para hacer de la calificación la parte más fácil de tu día.",
    "feat.vision.title": "Escaneo por Visión por Computadora",
    "feat.vision.desc": "Algoritmos avanzados de OCR digitalizan ensayos escritos a mano y hojas de respuestas con un 99.8% de precisión.",
    "feat.realtime.title": "Evaluación en Tiempo Real",
    "feat.realtime.desc": "El procesamiento instantáneo significa que las calificaciones están listas segundos después del envío.",
    "feat.analytics.title": "Analítica Profunda",
    "feat.analytics.desc": "Ve más allá de las puntuaciones simples. Identifica brechas de conocimiento y visualiza el crecimiento del rendimiento.",
    "feat.criteria.title": "Criterios Estandarizados",
    "feat.criteria.desc": "Garantiza la equidad con una IA que aplica rúbricas de calificación consistentes en cada examen.",
    "feat.scale.title": "Escalabilidad Global",
    "feat.scale.desc": "Construido para escalar. Ya sea para una sola aula o una corporación multinacional, nuestra infraestructura se adapta.",
    "feat.workload.title": "Reducción de Carga de Trabajo",
    "feat.workload.desc": "Recupera cientos de horas por semestre. Deja que la IA se encargue de la calificación mientras tú te concentras en la enseñanza.",
    "stats.gradingTime": "Reducción en Tiempo de Calif.",
    "stats.papers": "Exámenes Procesados Diariamente",
    "stats.accuracy": "Tasa de Precisión",
    "stats.uptime": "Disponibilidad del Sistema",

    // Paper To Digital
    "p2d.eyebrow": "Flujo de Digitalización",
    "p2d.title.1": "Físico a Digital",
    "p2d.title.2": "en milisegundos.",
    "p2d.subtitle": "Mira cómo nuestra visión por computadora transforma exámenes físicos en datos estructurados y analizables.",
    "p2d.rawInput": "Entrada Bruta",
    "p2d.processing": "Procesando",
    "p2d.structuredData": "Datos Estructurados",
    "p2d.insights": "Insights Instantáneos",
    "p2d.genReport": "Generando Informe...",

    // How It Works
    "hiw.eyebrow": "Escáner Móvil",
    "hiw.title.1": "Corrige hojas de respuestas con",
    "hiw.title.2": "solo tu cámara.",
    "hiw.score": "Nota",
    "hiw.step1.title": "Apunta y Captura",
    "hiw.step1.desc": "Usa la aplicación móvil para escanear pruebas. Sin escáneres especiales, solo tu teléfono inteligente.",
    "hiw.step2.title": "Corrección Instantánea",
    "hiw.step2.desc": "Nuestra visión por computadora identifica burbujas llenas al instante. Maneja borrones y garabatos con un 99% de precisión.",
    "hiw.step3.title": "Libreta Automática",
    "hiw.step3.desc": "Las calificaciones se sincronizan automáticamente con tu libreta de calificaciones digital.",

    // Essay Grading
    "essay.badge": "Calificación de Ensayos IA",
    "essay.title": "Comentarios detallados en cada frase.",
    "essay.subtitle": "Nuestra IA lee específicamente para tu rúbrica. Destaca errores gramaticales, detecta la fuerza de la tesis y proporciona comentarios procesables.",
    "essay.card.correction.title": "Corrección",
    "essay.card.correction.desc": "Identifica errores gramaticales, sintácticos y fácticos al instante.",
    "essay.card.praise.title": "Elogio",
    "essay.card.praise.desc": "Destaca argumentos sólidos y buen uso de la evidencia.",
    "essay.doc.title": "El Impacto de la Revolución Industrial",
    "essay.doc.p1": "La Revolución Industrial fue un período de gran industrialización que tuvo lugar a finales del siglo XVIII y principios del XIX.",
    "essay.doc.highlight1": "Comenzó en Gran Bretaña y se extendió rápidamente al mundo.",
    "essay.doc.p2": "Este período vio la mecanización de la agricultura y la fabricación textil y una revolución en la energía.",
    "essay.doc.p3": "Sin embargo, hubo muchos efectos negativos.",
    "essay.doc.highlight2": "La contaminación era muy mala y causó problemas.",
    "essay.doc.p4": "Aunque se logró el crecimiento económico, el costo social fue alto para la clase trabajadora que vivía en ciudades abarrotadas.",
    "essay.sidebar.title": "Comentarios de la IA",
    "essay.sidebar.tooltip.title": "Cómo funciona",
    "essay.sidebar.tooltip.desc": "Nuestros modelos de Procesamiento de Lenguaje Natural están entrenados en miles de rúbricas académicas para detectar estructura argumentativa y consistencia fáctica.",
    "essay.feedback.thesis": "Tesis Fuerte",
    "essay.feedback.thesis.desc": "Declaración de apertura clara identificando períodos clave.",
    "essay.feedback.vocab": "Vocabulario",
    "essay.feedback.vocab.desc": "\"Muy mala\" es vago. Considere \"perjudicial\" o \"nociva\".",
    "essay.score": "Nota",

    // Class Analytics
    "analytics.chart.title": "Análisis de Brechas",
    "analytics.chart.subtitle": "Estudiante vs. Promedio de Clase",
    "analytics.chart.class": "Clase",
    "analytics.chart.student": "Estudiante",
    "analytics.alert.title": "Intervención Necesaria",
    "analytics.alert.desc": "Las puntuaciones de vocabulario están un 20% por debajo del promedio.",
    "analytics.badge": "Crecimiento Enfocado",
    "analytics.title.1": "No solo califiques.",
    "analytics.title.2": "Entiende.",
    "analytics.subtitle": "Ve más allá de una simple calificación. Nuestro motor analítico desglosa el rendimiento por habilidades específicas.",
    "analytics.card1.title": "Dominio de Habilidades",
    "analytics.card1.desc": "Rastrea la competencia en temas específicos como 'Pensamento Crítico' o 'Álgebra'.",
    "analytics.card2.title": "Tendencias",
    "analytics.card2.desc": "Visualiza el progreso durante el semestre para validar los métodos de enseñanza.",
    // Topics & Insights
    "analytics.topic.grammar": "Gramática",
    "analytics.topic.logic": "Lógica",
    "analytics.topic.creativity": "Creatividad",
    "analytics.topic.evidence": "Evidencia",
    "analytics.topic.structure": "Estructura",
    "analytics.topic.vocab": "Vocabulario",
    "analytics.insight.grammar": "Fuerte dominio de las reglas de sintaxis.",
    "analytics.insight.logic": "El flujo de argumentos es ligeramente inconsistente.",
    "analytics.insight.creativity": "Perspectiva única, bien presentada.",
    "analytics.insight.evidence": "Las citas son precisas y relevantes.",
    "analytics.insight.structure": "Las transiciones de párrafo necesitan trabajo.",
    "analytics.insight.vocab": "Elección de palabras repetitiva detectada.",

    // Curriculum Breakdown
    "curr.eyebrow": "Insights Curriculares",
    "curr.title": "Rendimiento del Área al Tema",
    "curr.subtitle": "Profundiza en los datos. Ve exactamente qué contenidos específicos—como la 'Revolución Industrial'—dominan los estudiantes.",
    "curr.col1": "Área de Estudio",
    "curr.col2": "Disciplina",
    "curr.col3": "Temas Específicos",
    "curr.area.humanities": "Humanidades",
    "curr.area.stem": "STEM",
    "curr.disc.history": "Historia",
    "curr.disc.geography": "Geografía",
    "curr.disc.math": "Matemáticas",
    "curr.disc.physics": "Física",
    "curr.topic.indrev": "Revolución Industrial",
    "curr.topic.stoneage": "Edad de Piedra",
    "curr.topic.coldwar": "Guerra Fría",
    "curr.topic.mapreading": "Lectura de Mapas",
    "curr.topic.urban": "Planificación Urbana",
    "curr.topic.algebra": "Álgebra Lineal",
    "curr.topic.calc": "Cálculo I",
    "curr.topic.mech": "Mecánica",
    "curr.topic.thermo": "Termodinámica",
    "curr.metric.efficiency": "Eficiencia",
    "curr.metric.mastery": "Dominio",
    "curr.badge.custom": "Personalizable",
    "curr.btn.edit": "Editar Diseño",
    "curr.btn.done": "Listo",
    "curr.btn.drill": "Profundizar",

    // Parent Portal
    "parent.badge": "Participación de los Padres",
    "parent.title.1": "Mantén a los padres informados,",
    "parent.title.2": "automáticamente.",
    "parent.subtitle": "Un puente entre el hogar y la escuela. Evalua proporciona un portal móvil dedicado para que los tutores vean calificaciones, asistencia y comentarios en tiempo real.",
    "parent.list.1": "Notificaciones instantáneas para tareas",
    "parent.list.2": "Mensajería directa y segura con profesores",
    "parent.list.3": "Acceso al portafolio digital del estudiante",
    "parent.btn.enable": "Habilitar Acceso a Padres",
    "parent.btn.demo": "Enviar Actualización",
    "parent.demo.hint": "Toca \"Enviar Actualización\" para interactuar con la demostración.",
    "parent.phone.header": "Portal de Padres",
    "parent.phone.sub": "Mis Estudiantes",
    "parent.notif.grade.title": "Nueva Calificación",
    "parent.notif.grade.sub": "Matemáticas Intermedias",
    "parent.notif.event.title": "Evento Próximo",
    "parent.notif.event.sub": "Feria de Ciencias",
    "parent.nav.feed": "Feed",
    "parent.nav.plan": "Plan",
    "parent.nav.chat": "Chat",

    // Dashboard Preview
    "dash.eyebrow": "Visión Ejecutiva",
    "dash.title": "Datos que impulsan mejores decisiones.",
    "dash.subtitle": "Para administradores y jefes de departamento, obtén una vista panorámica del rendimiento institucional. Rastrea el progreso a lo largo del tiempo y compara cohortes.",
    "dash.list.1": "Alineación automática de rúbricas",
    "dash.list.2": "Alertas de detección de plagio",
    "dash.list.3": "Seguimiento longitudinal del rendimiento",
    "dash.list.4": "Integración perfecta con LMS",
    "dash.btn": "Explorar Analítica",
    "dash.vis.header": "Rendimiento de la Institución",
    "dash.vis.period": "Últimos 30 Días",
    "dash.vis.avg": "Promedio",
    "dash.vis.graded": "Calificados",
    "dash.vis.pending": "Pendientes",

    // Pricing
    "pricing.eyebrow": "Planes y Precios",
    "pricing.title": "Precios simples para",
    "pricing.title.span": "cada aula.",
    "pricing.subtitle": "Elige el plan que mejor se adapte a tus necesidades. Sin cargos ocultos, cancela en cualquier momento.",
    "pricing.monthly": "Mensual",
    "pricing.yearly": "Anual",
    "pricing.save": "Ahorra 20%",
    "pricing.free.title": "Gratis",
    "pricing.free.price": "0€",
    "pricing.free.period": "/mes",
    "pricing.free.desc": "Perfecto para profesores individuales que prueban la calificación por IA.",
    "pricing.free.btn": "Empezar",
    "pricing.free.f1": "Acceso a la App Móvil",
    "pricing.free.f2": "100 Exámenes / mes",
    "pricing.free.f3": "Corrección Básica de Hojas",
    "pricing.free.f4": "Soporte por Correo",
    "pricing.pro.title": "Pro",
    "pricing.pro.price": "29€",
    "pricing.pro.period": "/mes",
    "pricing.pro.desc": "Para usuarios avanzados que necesitan analíticas y calificación de ensayos.",
    "pricing.pro.btn": "Prueba Gratis",
    "pricing.pro.badge": "Más Popular",
    "pricing.pro.f1": "Exámenes Ilimitados",
    "pricing.pro.f2": "Calificación de Ensayos IA",
    "pricing.pro.f3": "Analítica de Clase",
    "pricing.pro.f4": "Portal de Padres",
    "pricing.pro.f5": "Exportación LMS (CSV)",
    "pricing.ent.title": "Enterprise",
    "pricing.ent.price": "A Medida",
    "pricing.ent.period": "",
    "pricing.ent.desc": "Para escuelas y distritos que requieren SSO e integraciones personalizadas.",
    "pricing.ent.btn": "Contactar Ventas",
    "pricing.ent.f1": "Todo lo de Pro",
    "pricing.ent.f2": "SSO y Seguridad Personalizada",
    "pricing.ent.f3": "Integración LMS Directa",
    "pricing.ent.f4": "Analítica Distrital",
    "pricing.ent.f5": "Gerente de Éxito Dedicado",

    // Enterprise
    "ent.eyebrow": "Edición Enterprise",
    "ent.title": "Construido para escalar, seguro para instituciones.",
    "ent.subtitle": "Opciones de implementación personalizadas, integración SSO y garantías respaldadas por SLA para distritos y universidades.",
    "ent.btn": "Contactar Ventas",
    "ent.feat1.title": "Seguridad de Grado Bancario",
    "ent.feat1.desc": "Tus datos de estudiantes están encriptados en reposo y en tránsito. Cumplimos con SOC2 Tipo II y estamos certificados por FERPA.",
    "ent.feat1.l1": "Cumple con SOC2 Tipo II",
    "ent.feat1.l2": "Listo para FERPA y GDPR",
    "ent.feat1.l3": "Encriptación de extremo a extremo",
    "ent.feat2.title": "SSO Sin Problemas",
    "ent.feat2.desc": "Integra con tu proveedor de identidad existente. Soportamos SAML, OAuth y OIDC.",
    "ent.feat3.title": "Infraestrutura Privada",
    "ent.feat3.desc": "Opción para implementación en VPC dedicada o contenedorización local para máxima soberania de datos.",
    "ent.feat3.l1": "SLA de 99.99% de Tiempo de Actividad",
    "ent.feat3.l2": "Gerente de Éxito Dedicado",
    "ent.feat3.l3": "Límites de API Personalizados",
    "ent.integrations": "Funciona con las herramientas que ya usas",

    // CTA
    "cta.title": "¿Listo para modernizar tu proceso de evaluación?",
    "cta.subtitle": "Únete a más de 500 instituciones educativas que ahorran tiempo con Evalua AI.",
    "cta.btn.start": "Empieza Gratis",
    "cta.btn.sales": "Contactar Ventas",

    // Footer
    "footer.desc": "Empoderando a los educadores con sistemas de evaluación automatizada de alta precisión. Construido para instituciones modernas.",
    "footer.platform": "Plataforma",
    "footer.company": "Empresa",
    "footer.rights": "© 2024 Evalua AI Inc. Todos los derechos reservados."
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('EN');

  const t = (key: string): string => {
    // @ts-ignore
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};